### ISSUE TITLE
Xposed Cmcallrecord

### ISSUE THREAD

**Issue by zishanashraf** [hawst/CMCallRecord#1]
Hello, 
I am using cm12.1 tamesek on note 3 n9005 when I call record, it gives an error "Fail to start call recording"

**Comment by hawst** [comment]
Could you provide logcat ?

**Comment by zishanashraf** [comment]
Hello,

Thank for the quick reply, here is the logcat

--------- beginning of main
E/Xposed  (12525): java.io.FileNotFoundException:
/storage/emulated/0/replace.map: open failed: EACCES (Permission denied)
E/Xposed  (12525): at libcore.io.IoBridge.open(IoBridge.java:459)
E/Xposed  (12525): at
java.io.FileInputStream.<init>(FileInputStream.java:76)
E/Xposed  (12525): at
java.io.FileInputStream.<init>(FileInputStream.java:103)
E/Xposed  (12525): at
de.galaxyinabox.xrenamer.CalledByXposed.handleInitPackageResources(CalledByXposed.java:23)
E/Xposed  (12525): at
de.robv.android.xposed.IXposedHookInitPackageResources$Wrapper.handleInitPackageResources(IXposedHookInitPackageResources.java:20)
E/Xposed  (12525): at
de.robv.android.xposed.callbacks.XC_InitPackageResources.call(XC_InitPackageResources.java:28)
E/Xposed  (12525): at
de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
E/Xposed  (12525): at
de.robv.android.xposed.XposedBridge$7.afterHookedMethod(XposedBridge.java:350)
E/Xposed  (12525): at
de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:682)
E/Xposed  (12525): at
android.app.ResourcesManager.getTopLevelResources(<Xposed>)
E/Xposed  (12525): at
android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1671)
E/Xposed  (12525): at android.app.LoadedApk.getResources(LoadedApk.java:533)
E/Xposed  (12525): at android.app.ContextImpl.<init>(ContextImpl.java:2342)
E/Xposed  (12525): at
android.app.ContextImpl.createAppContext(ContextImpl.java:2288)
E/Xposed  (12525): at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:4425)
E/Xposed  (12525): at
de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native
Method)
E/Xposed  (12525): at
de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)
E/Xposed  (12525): at
android.app.ActivityThread.handleBindApplication(<Xposed>)
E/Xposed  (12525): at
android.app.ActivityThread.access$1600(ActivityThread.java:153)
E/Xposed  (12525): at android.app.ActivityThread$

**Comment by hawst** [comment]
As i can see issue is related to xposed itself, somehow it cannot access file "/storage/emulated/0/replace.map", that is internal storage. I suggest you ask temasek or try to install official CM12.1 and check if it work there.

**Comment by zishanashraf** [comment]
Is there a way I can allow permission since it says denied. any help would
be appreciated.

**Comment by zishanashraf** [comment]
I can edit permission from root explorer, but what mods to make

**Comment by panxe** [comment]
Support for CM13, no urgency.
